spring.application.name=shopsphere-backend

spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truespring.application.name=shopsphere-backend
logging.level.com.shopsphere=DEBUG
logging.file.name=logs/shopsphere.log